# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
- master

pool:
  vmImage: ubuntu-20.04

variables:
  repositoryName: 'websocketchatacr'
  imageName: 'websockets-chat-example'
  DOCKER_BUILDKIT: 1

steps:
- task: Docker@2
  displayName: 'Build server image and push image'
  inputs:
    repository: $(imageName)
    containerRegistry: $(repositoryName)
    command: buildAndPush
    Dockerfile: examples/azure-websockets/Dockerfile.server
    buildContext: $(Build.Repository.LocalPath)
    
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
