# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
- master

pool:
  vmImage: ubuntu-20.04

variables:
  kubernetesConnection: 'websocket-chat-cluster'
  repositoryName: 'websocketchatacr'
  repositoryUrl: 'websocketchatacr.azurecr.io'
  imageName: 'websockets-chat-example'
  DOCKER_BUILDKIT: 1

steps:
- task: Docker@2
  displayName: 'Build server image and push image'
  inputs:
    repository: $(imageName)
    containerRegistry: $(repositoryName)
    command: buildAndPush
    Dockerfile: examples/azure-websockets/Dockerfile.server
    buildContext: $(Build.Repository.LocalPath)
    
- task: KubernetesManifest@0
  displayName: Deploy
  inputs:
    kubernetesServiceConnection: $(kubernetesConnection)
    namespace: default
    manifests: |
      examples/azure-websockets/manifests/service-chat.yaml
      examples/azure-websockets/manifests/deployment-chat.yaml
    containers: |
      $(repositoryUrl)/$(imageName):$(Build.BuildId)
