apiVersion: v1
kind: Service
metadata:
  name: websockets-chat-backend 
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 12345
  selector:
    app: websockets-chat-backend
