apiVersion: v1
kind: Service
metadata:
  name: websockets-chat-backend 
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 12345
    protocol: TCP
  selector:
    app: websockets-chat-backend
